// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class moviegenretable_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moviegenretable_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201801311809144_moviegenretable_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
